//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSach_63134277.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int ma_CDH { get; set; }
        public Nullable<int> ma_DH { get; set; }
        public Nullable<int> ma_Sach { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> tong { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
